name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: kernel version
      run: uname -r
    - name: Build
      run: go build
    - name: ls
      run: ls -l
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webSocks5-artifact
        path: webSocks5
