# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: kernel version
      run: uname -r
    - name: Build server.go
      run: go build server.go
    - name: ls
      run: ls -l
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: server-artifact
        path: server
